name: CI/CD
on:
  push:
  pull_request:
  schedule:
    - cron: '15 9 25 * *' # Monthly at 9:15am on the 25th
jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the Image
        run: ./build
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push the Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker push -a sqitch/sqitch
